language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.3
  - 5.2
  - hhvm

env:
    # nightly:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1
    # latest stable:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    # earliest supported version with a non-buggy unit test suite:
    - WP_VERSION=3.7 WP_MULTISITE=0
    - WP_VERSION=3.7 WP_MULTISITE=1

matrix:
   exclude:
        # don't test 3.7 on hiphop:
        - php: hhvm
          env: WP_VERSION=3.7 WP_MULTISITE=0
        - php: hhvm
          env: WP_VERSION=3.7 WP_MULTISITE=1
        # don't test 3.7 on PHP 7:
        - php: 7.0
          env: WP_VERSION=3.7 WP_MULTISITE=0
        - php: 7.0
          env: WP_VERSION=3.7 WP_MULTISITE=1
        # don't test 3.7 on PHP 7.1:
        - php: 7.1
          env: WP_VERSION=3.7 WP_MULTISITE=0
        - php: 7.1
          env: WP_VERSION=3.7 WP_MULTISITE=1
   allow_failures:
        # allow failures on nightlies:
        - env: WP_VERSION=nightly WP_MULTISITE=0
        - env: WP_VERSION=nightly WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
